// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4FR48jeSc0IGsuumO-Al9Dq2CdsdMcCI',
    appId: '1:703243990200:web:003a7d66da71b7fb93704d',
    messagingSenderId: '703243990200',
    projectId: 'w04-tk',
    authDomain: 'w04-tk.firebaseapp.com',
    storageBucket: 'w04-tk.firebasestorage.app',
    measurementId: 'G-1SWBG6DJK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGl6_9nx1xZ-F4nhBt3LTZBlQ0KRcflaI',
    appId: '1:703243990200:android:93c76ca6239b1c2193704d',
    messagingSenderId: '703243990200',
    projectId: 'w04-tk',
    storageBucket: 'w04-tk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXboXnJ0B05qxCuSoxOdVzpYxK26X1OU8',
    appId: '1:703243990200:ios:3e6cdc002d8a0edd93704d',
    messagingSenderId: '703243990200',
    projectId: 'w04-tk',
    storageBucket: 'w04-tk.firebasestorage.app',
    iosBundleId: 'com.example.testapi01',
  );
}
